---
# tasks for sysdev.zabbix-agent
- name: Install require packages
  become: true
- name:  Install All packages
  yum:  name={{ item.package }}
        state={{ item.state }}
  with_items:
    - { package: "*" , state: "latest" }
    - { package: "epel-release , state: "present" }
    - { package: "http://repo.zabbix.com/zabbix/3.5/rhel/7/x86_64/zabbix-release-3.5-1.el7.noarch.rpm", state: "present" } 
    - { package: "zabbix-agent" , state: "present" } 

